events {}

http {

    server {
        listen 80;
        return 301 https://$host$request_uri;
    }

    server {

        listen 443 ssl;

        ssl_certificate /etc/nginx/ssl/cert.pem;
        ssl_certificate_key /etc/nginx/ssl/key.pem;

        location / {
            proxy_pass http://frontend:3000;
        }

        location /api/ {
            proxy_pass http://backend:5000/;
        }

        location /uploads/ {
            proxy_pass http://backend:5000/uploads/;
        }

    }
}